# fly.toml app configuration file generated for honovel on 2026-09-17T07:44:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'honovel'
primary_region = 'ams'

[build]

[env]
  APP_PORT = '8080'
  PORT = '8080'
  APP_NAME = 'Honovel'
  APP_ENV = 'production'
  APP_DEBUG = 'false'
  APP_URL = 'https://honovel.fly.dev'
  DB_CONNECTION = 'mysql'
  BROADCAST_DRIVER = 'log'
  CACHE_DRIVER = 'redis'
  QUEUE_CONNECTION = 'sync'
  SESSION_DRIVER = 'cache'
  REDIS_CLIENT = 'upstash'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
